### ISSUE TITLE
The documentation or guide is very confusing

### ISSUE THREAD

**Issue by wilbyang** [ahamez/protox#207]
from `mix help protox.generate`, it seems we can only generate the code by `mix protox.generate --output-path=lib/message.ex --include-path=.
message.proto` but from https://hexdocs.pm/protox/Protox.html, we can do something like 
```
defmodule Dummy do
  use Protox,
    files: [
      "./defs/foo.proto",
      "./defs/bar.proto",
      "./defs/baz/fiz.proto",
    ]
end
```
, while there is no information on how to generate from this `Dummy` module

**Comment by ahamez** [comment]
Hi there!
If you want to generate source code, it's only possible with the mix task. When using directly the macro, it generates Elixir modules you call directly. I'll make sure to update the documentation to make it more clear!
Does it answer your question?
