### ISSUE TITLE
Feature request: ability to ignore unknown fields and not have __uf__ properties in structs

### ISSUE THREAD

**Issue by petrohi** [ahamez/protox#22]

**Comment by ahamez** [comment]
I wanted to do it for a long time 😉. Thanks for bringing this issue!

**Comment by petrohi** [comment]
Thank you for adding this so quickly!

Question: is there a way to specify this option with protox.generate?

**Comment by ahamez** [comment]
Yes, it looks like it's possible, I have something on commit 46ecdeeee1. You just need to add the option `--keep-unknown-fields=false` to the command line arguments. Can you give it a try to tell me if it works for you?

**Comment by petrohi** [comment]
When I do

`mix protox.generate --keep-unknown-fields=false --output-path=lib/grpc_dummy2.pb.ex priv/protos/grpc_dummy2.proto`

I get

`Failed to generate code: {[output_path: "lib/grpc_dummy2.pb.ex"], ["priv/protos/grpc_dummy2.proto"], [{"--keep-unknown-fields", nil}]}`

**Comment by petrohi** [comment]
My apologies--I did not get the latest master--it works!

**Comment by ahamez** [comment]
🙂 I'll release it properly later in the week
