### ISSUE TITLE
protox generates nested lists (was: Strange behavior when encoding complex nested struct)

### ISSUE THREAD

**Issue by seanmor5** [ahamez/protox#71]
Hey there! I'm using Protox over at [axon_onnx](https://github.com/elixir-nx/axon_onnx). Great library! It was really easy to get up and running.

I'm trying to encode and decode data based on this protocol: https://github.com/onnx/onnx/blob/master/onnx/onnx.proto

Everything works fine for decoding; however, when I try to encode models, it produces a strange nested list. As an example, I tried to read, decode, and then encode a model to determine if the result was the same and it was not. Specifically, I downloaded this model: https://github.com/onnx/models/blob/master/vision/classification/resnet/model/resnet18-v1-7.onnx

And then did:

```elixir
iex(1)> data = File.read!("resnet18-v1-7.onnx")
<<8, 3, 58, 244, 218, 169, 22, 10, 172, 1, 10, 4, 100, 97, 116, 97, 10, 22, 114,
  101, 115, 110, 101, 116, 118, 49, 53, 95, 99, 111, 110, 118, 48, 95, 119, 101,
  105, 103, 104, 116, 18, 19, 114, 101, 115, 110, 101, 116, 118, 49, ...>>
iex(2)> decoded = Onnx.ModelProto.decode!(data)
%Onnx.ModelProto{...everything is fine here...}
iex(3) encoded = Onnx.ModelProto.encode!(decoded)
[
  [
    [[], "\b", <<3>>],
    ":",
    [
      [<<241>>, [<<218>>, [<<169>>, <<22>>]]],
      <<10, 170, 1, 10, 4, 100, 97, 116, 97, 10, 22, 114, 101, 115, 110, 101,
        116, 118, 49, 53, 95, 99, 111, 110, 118, 48, 95, 119, 101, 105, 103,
        104, 116, 18, 19, 114, 101, 115, 110, 101, 116, 118, 49, 53, ...>>
    ]
  ],
  [[], "B", [<<2>>, <<16, 8>>]]
]
```

Not sure what's going wrong, but I am unable to encode even basic models. Please let me know if I can provide any additional info to help fix this :)

**Comment by ahamez** [comment]
Hello! I'm glad to know that you found the library easy to use :-)

The output you got is expected: protox outputs [IO data](https://hexdocs.pm/elixir/IO.html#module-use-cases-for-io-data), a data structure to optimize the generation of large volumes of data.
All output functions should be able to take this kind of data as a parameter. In your case, if you want to write `encoded` to a file:
```elixir
iex> data = File.read!("resnet18-v1-7.onnx")
iex> decoded = Onnx.ModelProto.decode!(data)
iex> encoded = Onnx.ModelProto.encode!(decoded)
iex> {:ok, file} = File.open("msg.bin", [:write])
iex> IO.binwrite(file, encoded)
```

If you want a good old binary, use `:binary.list_to_bin()`:
```elixir
iex> encoded = decoded |> Onnx.ModelProto.encode!() |> :binary.list_to_bin()
<<8, 3, 58, 244, 218, 169, 22, 10, 172, 1, 10, 4, 100, 97, 116, 97, 10, 22, 114,
  101, 115, 110, 101, 116, 118, 49, 53, 95, 99, 111, 110, 118, 48, 95, 119, 101,
  105, 103, 104, 116, 18, 19, 114, 101, 115, 110, 101, 116, 118, 49, ...>>
iex>  data == encoded
true
```

Does this answer your question?

BTW, I really enjoyed your book on genetic algorithms, and congrats for your work on Nx ;-)

**Comment by seanmor5** [comment]
Ahh that makes sense - sorry for the easy question! Thank you so much, this is exactly what I needed! I am glad you enjoyed the book :)
