### ISSUE TITLE
[BUG] README.md contains misleading examples

### ISSUE THREAD

**Issue by YarNayar** [ahamez/protox#73]
Hi there!
Trying the library, happen to notice this:

**Describe the bug**
README says do the `Protox.encode(msg)` while the correct version would be `Protox.Encode.encode(msg)`, probably same with decode.

It is written correctly in Elixir docs, but wrong(outdated?) in README on github.

Cheers!

**Comment by ahamez** [comment]
Hi! Indeed, the documentation on Github is for the current development version. I've made the mistake to merge a branch too early 😓
The correct documentation for version 1.5.1 is on [hex.pm](https://hexdocs.pm/protox/readme.html).
I'll add a warning in the README about this.
